/*
DO NOT DELETE!!!
*/

/*
THIS FILE IS HERE BECAUSE
WEBPACK REQURIES AN ENTRY POINT IN ORDER TO EXECUTE
*/

/*
THIS PROJECT REQURIES A 'PRE-BUILD' SCRIPT
TO GENERATE A MANIFEST FILE CONTAINING SITE ASSET MAPPINGS
*/

/*
THE SUBSEQUENT WEBPACK SCRIPT GETS ALL STATIC FILES
WHICH, IN TURN, HAVE REFERENCES TO
THE PREVIOUSLY GENERATED ASSETS MANIFEST FILE
*/

/*
IN SUMMARY, STATIC ASSETS DEPEND ON THE ASSETS MANIFEST FILE
*/

/*
THIS IS ONLY APPLICABLE IF YOUR SCRIPT NEEDS TO ACCESS
ASSETS DYNAMICALLY THAT IS NOT THROUGH YOUR MARKUP (EJS/HTML)
*/
